# # syntax = docker/dockerfile:1

# ARG NODE_VERSION=20

# FROM node:${NODE_VERSION}-slim

# ENV NODE_ENV=development

# WORKDIR /app

# RUN npm install -g pnpm

# COPY . .

# RUN pnpm install


# CMD [ "pnpm", "dev" ]