version: '3.9'

services:
  directus:
      image: directus/directus:latest
      container_name: directus_app
      environment:
        PUBLIC_URL: ${DIRECTUS_PUBLIC_URL}
        KEY: ${DIRECTUS_KEY}
        SECRET: ${DIRECTUS_SECRET}
        DB_CLIENT: pg
        DB_HOST: ${POSTGRES_HOST}
        DB_PORT: ${POSTGRES_PORT}
        DB_DATABASE: ${POSTGRES_DB}
        DB_USER: ${POSTGRES_USER}
        DB_PASSWORD: ${POSTGRES_PASSWORD}
        ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
        ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
        CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_ANCESTORS: ${CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_ANCESTORS}
        CORS_ENABLED: ${CORS_ENABLED}
        CORS_ORIGIN: ${CORS_ORIGIN}
        STORAGE_AZURE_ACCOUNT_KEY: ${STORAGE_AZURE_ACCOUNT_KEY}
        STORAGE_AZURE_ACCOUNT_NAME: ${STORAGE_AZURE_ACCOUNT_NAME}
        STORAGE_AZURE_CONTAINER_NAME: ${STORAGE_AZURE_CONTAINER_NAME}
        STORAGE_AZURE_DRIVER: ${STORAGE_AZURE_DRIVER}
        STORAGE_AZURE_ENDPOINT: ${STORAGE_AZURE_ENDPOINT}
        STORAGE_LOCATIONS: ${STORAGE_LOCATIONS}
        AUTH_PROVIDERS: ${AUTH_PROVIDERS}
        AUTH_GOOGLE_DRIVER: ${AUTH_GOOGLE_DRIVER}
        AUTH_GOOGLE_CLIENT_ID: ${AUTH_GOOGLE_CLIENT_ID}
        AUTH_GOOGLE_CLIENT_SECRET: ${AUTH_GOOGLE_CLIENT_SECRET}
        AUTH_GOOGLE_ISSUER_URL: ${AUTH_GOOGLE_ISSUER_URL}
        AUTH_GOOGLE_IDENTIFIER_KEY: ${AUTH_GOOGLE_IDENTIFIER_KEY}
        AUTH_GOOGLE_ICON: ${AUTH_GOOGLE_ICON}
        AUTH_GOOGLE_LABEL: ${AUTH_GOOGLE_LABEL}
        AUTH_GOOGLE_ALLOW_PUBLIC_REGISTRATION: ${AUTH_GOOGLE_ALLOW_PUBLIC_REGISTRATION}
        AUTH_GOOGLE_DEFAULT_ROLE_ID: ${AUTH_GOOGLE_DEFAULT_ROLE_ID}
        AUTH_GOOGLE_REDIRECT_ALLOW_LIST: ${AUTH_GOOGLE_REDIRECT_ALLOW_LIST}
      ports:
        - "8055:8055"
      restart: unless-stopped
      # networks:
      #   - directus_network
      labels:
        - "com.example.service=Directus Service"
      
#   nuxt:
#     build:
#       context: .
#       dockerfile: Dockerfile.dev
#     container_name: nuxt_app
#     # environment:
#     #   API_URL: ${API_URL}
#     #   DIRECTUS_URL: ${DIRECTUS_URL}
#     volumes:
#       - ./:/app
#     ports:
#       - "3000:3000"
#       - "24678:24678"
#     restart: unless-stopped
#     networks:
#       - directus_network
#     depends_on:
#       - directus
#     labels:
#       - "com.example.service=Nuxt App Service"

# networks:
#   directus_network:
#     driver: bridge
